# Generated by Django 5.1.1 on 2024-10-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_point_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
