# Generated by Django 5.1.1 on 2024-10-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_payment_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
